version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    container_name: prisma-server
    restart: always
    ports:
      - "${PRISMA_PORT}:${PRISMA_PORT}"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: ${PRISMA_PORT}
        databases:
          default:
            connector: ${PRISMA_DB_CONNECTOR}
            uri: ${PRISMA_DB_URI}
  mongo:
    image: mongo:latest
    container_name: prisma-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo: ~
